import Head from "next/head";
import Navbar from "@/pages/assets/Navbar/Navbar"
import styles from "@/styles/Home.module.scss"
import HeroSection from "./assets/HeroSection/HeroSection";
import Footer from "./assets/Footer/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Demo atoms</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.wrapper} >
        <Navbar/>
        <HeroSection/>
        <Footer/>

      </main>
    </>
  );
}
